name = "toolkit-api"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "TOOLKIT_KV"
id = "4ac504acc7314562874006dadebf6822"

[env.production]
routes = [
  { pattern = "*.tools.vanhci.top", zone_name = "vanhci.top" }
]